import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { getData } from "./api/profiles";

export default function Home({ profiles }) {
  const [currentUser, setCurrentUser] = useState("quibler");
  const [page, setPage] = useState("quibler");
  return (
    <div className="w-full h-full grid place-content-center gap-10">
      <Head>
        <title>Doge Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl">Whose profile you wanna see?</h1>
      <div className="text-xl flex flex-wrap justify-center items-center gap-10">
        {profiles.map((profile) => {
          return (
            <Link key={profile._id} href={`/${profile.nickname}`}>
              <a className="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
                {profile.nickname}
              </a>
            </Link>
          );
        })}
      </div>
      <button className="text-green-700 hover:text-white border border-green-700 hover:bg-green-800 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-xl px-5 py-2.5 text-center mr-2 mb-2 dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-600 dark:focus:ring-green-800">
        Add New Doge Profile
      </button>
      {/* {page === "profile" ? (
        <ProfilePage profile={props} />
      ) : (
        <div></div>
      )} */}
    </div>
  );
}

export async function getServerSideProps() {
  const data = await getData();
  return {
    props: {
      profiles: JSON.parse(JSON.stringify(data)),
    },
  };
}
