import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import ProfilePage from "../components/ProfilePage.js";
import dbConnect from "../lib/dbConnect";
import { getData } from "./api/profiles";

export default function Home(props) {
  const [currentName, setCurrentName] = useState("");
  const [page, setPage] = useState("quibler");

  return (
    <div className={styles.container}>
      <Head>
        <title>quibler</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {page === "quibler" ? (
        <ProfilePage profile={props} />
      ) : (
        <div className="w-full h-full text-2xl grid place-content-center">
          <label>Your Metaverse Name</label>
          <input className="text-black" placeholder="quibler"></input>
        </div>
      )}
    </div>
  );
}

export async function getServerSideProps() {
  await dbConnect();
  const profile = await getData();
  return {
    props: JSON.parse(JSON.stringify(profile)),
  };
}
